src/objects/ClassLink__c.object
<CustomObject>
    <description>Represents the linkage from one file to another via an &quot;extends&quot;, &quot;implements&quot;, &quot;sees&quot;, and &quot;exceptions&quot;</description>
    <fields>
        <fullName>CodeInfoName__c</fullName>
        <formula>CodeInfo__r.FileName__c</formula>
        <label>Code Info Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeInfo__c</fullName>
        <description>This is the link to the file that &quot;contains&quot; the link.</description>
        <inlineHelpText>This is the link to the file that &quot;contains&quot; the link.</inlineHelpText>
        <label>Code Info</label>
        <referenceTo>CodeInfo__c</referenceTo>
        <relationshipLabel>Class Links</relationshipLabel>
        <relationshipName>ClassLinks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CoreApexLink__c</fullName>
        <description>Web address of a core Apex class or interface that this links to.</description>
        <inlineHelpText>Web address of a core Apex class or interface that this links to.</inlineHelpText>
        <label>Core Apex Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LinksToName__c</fullName>
        <description>The name of the class or method that this link is in reference to.</description>
        <inlineHelpText>The name of the class or method that this link is in reference to.</inlineHelpText>
        <label>Links To Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinksTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the link to the file that Code Info file actually links to.</description>
        <inlineHelpText>This is the link to the file that Code Info file actually links to.</inlineHelpText>
        <label>Links To</label>
        <referenceTo>CodeInfo__c</referenceTo>
        <relationshipLabel>Class Links (Links To)</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedConstruct__c</fullName>
        <description>The method or inner class that the class link may related to.  For example, a @throws link does not belong to a class but rather a method of a class.</description>
        <inlineHelpText>The method or inner class that the class link may related to.  For example, a @throws link does not belong to a class but rather a method of a class.</inlineHelpText>
        <label>Related Construct</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of class link this record represents.  Is it an &quot;extends&quot;, an &quot;implements&quot;, a &quot;see&quot;, or an &quot;exception&quot;.</description>
        <inlineHelpText>The type of class link this record represents.  Is it an &quot;extends&quot;, an &quot;implements&quot;, a &quot;see&quot;, or an &quot;exception&quot;.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class Link</label>
    <nameField>
        <displayFormat>CLN-{0000000000}</displayFormat>
        <label>Class Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CodeInfo__c.object
<CustomObject>
    <description>Data object to store details about various sections of ApexClass objects</description>
    <fields>
        <fullName>ApexClassId__c</fullName>
        <description>The id of the ApexClass record that this ApexDoc describes</description>
        <externalId>true</externalId>
        <inlineHelpText>The id of the ApexClass record that this ApexDoc describes</inlineHelpText>
        <label>ApexClass ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <description>The name of the Apex Class or Interface that this record belongs to.</description>
        <externalId>true</externalId>
        <inlineHelpText>The name of the Apex Class or Interface that this record belongs to.</inlineHelpText>
        <label>File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <description>The type of data record this is.  It can be CLASS, METHOD, PROPERTY.</description>
        <inlineHelpText>The type of data record this is.  It can be CLASS, METHOD, PROPERTY.</inlineHelpText>
        <label>Model Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Code Info</label>
    <nameField>
        <displayFormat>CIN-{000000000}</displayFormat>
        <label>Code Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApexDocModelCompositeTransformer.cls
public class ApexDocModelCompositeTransformer
{
    public static ClassLinkModel createClassLinkModel(final ClassLink__c input)
    {
        ClassLinkModel output = new ClassLinkModel(ClassLinkModel.getTypeByName(input.Type__c), input.linksToName__c);

        output.setUrl( input.LinksTo__c == null ? input.CoreApexLink__c : '/'+input.LinksTo__c ) ;

        output.setFromUrl( '/' + input.CodeInfo__c);
        output.setFromName( input.CodeInfoName__c);

        return output;
    }

    public static ClassLink__c createClassLinkRecord(final ClassLinkModel input)
    {
        ClassLink__c classLinkRecord = new ClassLink__c();

        classLinkRecord.Type__c = input.getLinkType().name();
        classLinkRecord.LinksToName__c = input.getName();
        classLinkRecord.CoreApexLink__c = input.getUrl();

        return classLinkRecord;
    }

    public static list<ClassLink__c> createClassLinkRecords(final list<ClassLinkModel> input)
    {
        list<ClassLink__c> output = new list<ClassLink__c>();

        for (ClassLinkModel model : input)
        {
            output.add( createClassLinkRecord(model) );
        }

        return output;
    }

    public static list<ClassLink__c> createClassLinkRecords(final list<ClassLinkModel> input, final string apexConstructName)
    {
        list<ClassLink__c> output = new list<ClassLink__c>();

        ClassLink__c classLink = null;

        for (ClassLinkModel model : input)
        {
            classLink = createClassLinkRecord(model);
            classLink.RelatedConstruct__c = apexConstructName;
            output.add( classLink );
        }

        return output;
    }

    public static IFile convertSObjectToDomainModel(final CodeInfo__c input)
    {
        IFile output = null;

        if ( input != null )
        {
            try
            {
                Type modelType = Type.forName( input.ModelType__c );
    
                output = (IFile)JSON.deserialize( input.Json__c, modelType );
    
                output.setId(input.id);
            }
            catch (System.SObjectException soe)
            {
                throw new ApexDocModelCompositeTransformer.ApexDocModelTransformerException('The current Model Type for record id is not the correct type.');
            }            
        }

        return output;
    }

    public static CodeInfo__c convertDomainModelToSObject(final IFile input)
    {
        CodeInfo__c output = new CodeInfo__c();

        output.filename__c = input.getName();

        if (input instanceOf FileModel)
        {
            output.ModelType__c = ClassModel.class.getName();
        }
        else
        {
            output.ModelType__c = ((ApexConstructBaseModel)input).getClassType().getName();
        }

        output.ApexClassId__c = input.getApexFileId();
        
        if ( input instanceOf ApexConstructBaseModel )
        {
            output.JSON__c = JSON.serialize( (ApexConstructBaseModel)input );
        }

        return output;
    }

    /**
     *  @description This is the standard exception that will be thrown by the
     *      ApexDocModelCompositeTransformer class
     *  @since 1.0
     */
    public class ApexDocModelTransformerException extends Exception {}
}