src/objects/ClassLink__c.object
<CustomObject>
    <description>Represents the linkage from one file to another via an &quot;extends&quot;, &quot;implements&quot;, &quot;sees&quot;, and &quot;exceptions&quot;</description>
    <fields>
        <fullName>CodeInfoName__c</fullName>
        <formula>CodeInfo__r.FileName__c</formula>
        <label>Code Info Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CodeInfo__c</fullName>
        <description>This is the link to the file that &quot;contains&quot; the link.</description>
        <inlineHelpText>This is the link to the file that &quot;contains&quot; the link.</inlineHelpText>
        <label>Code Info</label>
        <referenceTo>CodeInfo__c</referenceTo>
        <relationshipLabel>Class Links</relationshipLabel>
        <relationshipName>ClassLinks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CoreApexLink__c</fullName>
        <description>Web address of a core Apex class or interface that this links to.</description>
        <inlineHelpText>Web address of a core Apex class or interface that this links to.</inlineHelpText>
        <label>Core Apex Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>LinksToName__c</fullName>
        <description>The name of the class or method that this link is in reference to.</description>
        <inlineHelpText>The name of the class or method that this link is in reference to.</inlineHelpText>
        <label>Links To Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LinksTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the link to the file that Code Info file actually links to.</description>
        <inlineHelpText>This is the link to the file that Code Info file actually links to.</inlineHelpText>
        <label>Links To</label>
        <referenceTo>CodeInfo__c</referenceTo>
        <relationshipLabel>Class Links (Links To)</relationshipLabel>
        <relationshipName>References</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedConstruct__c</fullName>
        <description>The method or inner class that the class link may related to.  For example, a @throws link does not belong to a class but rather a method of a class.</description>
        <inlineHelpText>The method or inner class that the class link may related to.  For example, a @throws link does not belong to a class but rather a method of a class.</inlineHelpText>
        <label>Related Construct</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The type of class link this record represents.  Is it an &quot;extends&quot;, an &quot;implements&quot;, a &quot;see&quot;, or an &quot;exception&quot;.</description>
        <inlineHelpText>The type of class link this record represents.  Is it an &quot;extends&quot;, an &quot;implements&quot;, a &quot;see&quot;, or an &quot;exception&quot;.</inlineHelpText>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Class Link</label>
    <nameField>
        <displayFormat>CLN-{0000000000}</displayFormat>
        <label>Class Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CodeInfo__c.object
<CustomObject>
    <description>Data object to store details about various sections of ApexClass objects</description>
    <fields>
        <fullName>FileName__c</fullName>
        <description>The name of the Apex Class or Interface that this record belongs to.</description>
        <externalId>true</externalId>
        <inlineHelpText>The name of the Apex Class or Interface that this record belongs to.</inlineHelpText>
        <label>File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Code Info</label>
    <nameField>
        <displayFormat>CIN-{000000000}</displayFormat>
        <label>Code Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClassLinksSelector.cls
public with sharing class ClassLinksSelector
    extends fflib_SObjectSelector
    implements IClassLinksSelector
{
    public static IClassLinksSelector newInstance()
    {
        return (IClassLinksSelector) Application.Selector.newInstance(ClassLink__c.SObjectType);
    }

    public list<Schema.SObjectField> getSObjectFieldList()
    {
        return new list<Schema.SObjectField>
        {
            ClassLink__c.Id,
            ClassLink__c.Name,
            ClassLink__c.CreatedDate,
            ClassLink__c.CreatedById,
            ClassLink__c.LastModifiedDate,
            ClassLink__c.LastModifiedById,
            ClassLink__c.CodeInfo__c,
            ClassLink__c.CodeInfoName__c,
            ClassLink__c.CoreApexLink__c,
            ClassLink__c.LinksTo__c,
            ClassLink__c.LinksToName__c,
            ClassLink__c.Type__c,
            ClassLink__c.RelatedConstruct__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return ClassLink__c.sObjectType;
    }

    public List<ClassLink__c> selectById(final set<ID> idSet)
    {
        return (List<ClassLink__c>) selectSObjectsById(idSet);
    }

    public list<ClassLink__c> selectByLinksNotResolved()
    {
        String query = string.format('select {0} ' +
                                       'from {1} ' +
                                      'where {2} = null ' +
                                         'or {3} = null ',
                                    new list<string>{
                                        getFieldListString(),
                                        getSObjectName(),
                                        ClassLink__c.LinksTo__c.getDescribe().getName(),
                                        ClassLink__c.CoreApexLink__c.getDescribe().getName()
                                    });

        return (List<ClassLink__c>) Database.query(query);
    }

    public list<ClassLink__c> selectByLinkTo(final id linkToId)
    {
        String query = string.format('select {0} ' +
                                       'from {1} ' +
                                      'where {2} = :linkToId',
                                    new list<string>{
                                        getFieldListString(),
                                        getSObjectName(),
                                        ClassLink__c.LinksTo__c.getDescribe().getName()
                                    });

        return (List<ClassLink__c>) Database.query(query);
    }

    public list<ClassLink__c> selectByApexClassNameParent(final set<string> fileNameSet)
    {
        String query = string.format('select {0} ' +
                                       'from {1} ' +
                                      'where {2} in (select id from {3} where {4} in :fileNameSet)',
                                    new list<string>{
                                        getFieldListString(),   // 0
                                        getSObjectName(),       // 1
                                        ClassLink__c.CodeInfo__c.getDescribe().getName(),   // 2
                                        CodeInfo__c.SObjectType.getDescribe().getName(),    // 3
                                        CodeInfo__c.FileName__c.getDescribe().getName()     // 4
                                    });

        return (List<ClassLink__c>) Database.query(query);
    }

}