src/objects/ClassLink__c.object
<CustomObject>
    <description>Represents the linkage from one file to another via an &quot;extends&quot;, &quot;implements&quot;, &quot;sees&quot;, and &quot;exceptions&quot;</description>
    <fields>
        <fullName>CodeInfo__c</fullName>
        <description>This is the link to the file that &quot;contains&quot; the link.</description>
        <inlineHelpText>This is the link to the file that &quot;contains&quot; the link.</inlineHelpText>
        <label>Code Info</label>
        <referenceTo>CodeInfo__c</referenceTo>
        <relationshipLabel>Class Links</relationshipLabel>
        <relationshipName>ClassLinks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class Link</label>
    <nameField>
        <displayFormat>CLN-{0000000000}</displayFormat>
        <label>Class Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CodeInfo__c.object
<CustomObject>
    <description>Data object to store details about various sections of ApexClass objects</description>
    <label>Code Info</label>
    <nameField>
        <displayFormat>CIN-{000000000}</displayFormat>
        <label>Code Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Application.cls
public class Application
{
    // SObject's used by the logic in this service, listed in dependency order
    private static list<Schema.SObjectType> SERVICE_SOBJECTS =
                    new list<Schema.SObjectType>
                    {
                        CodeInfo__c.SObjectType,
                        ClassLink__c.SObjectType,
                        Attachment.SObjectType
                    };

    // Configure and create the UnitOfWorkFactory for this Application
    public static final fflib_Application.UnitOfWorkFactory UnitOfWork =
        new fflib_Application.UnitOfWorkFactory(SERVICE_SOBJECTS);

    // Configure and create the ServiceFactory for this Application
    public static final fflib_Application.ServiceFactory Service =
        new fflib_Application.ServiceFactory(
            new Map<Type, Type> {
                    IApexDocsService.class => ApexDocsServiceImpl.class
                    });

    // Configure and create the SelectorFactory for this Application
    public static final fflib_Application.SelectorFactory Selector =
        new fflib_Application.SelectorFactory(
            new Map<SObjectType, Type> {
                    ApexClass.SObjectType => ApexClassesSelector.class,
                    CodeInfo__c.SObjectType => CodeInfosSelector.class,
                    ClassLink__c.SObjectType => ClassLinksSelector.class,
                    Attachment.SObjectType => AttachmentsSelector.class
                    });

    // Configure and create the DomainFactory for this Application
    public static final fflib_Application.DomainFactory Domain =
        new fflib_Application.DomainFactory(
            Application.Selector,
            new Map<SObjectType, Type> {
                    CodeInfo__c.SObjectType => CodeInfos.Constructor.class
                 });
}