src/objects/CodeInfo__c.object
<CustomObject>
    <description>Data object to store details about various sections of ApexClass objects</description>
    <fields>
        <fullName>ApexClassId__c</fullName>
        <description>The id of the ApexClass record that this ApexDoc describes</description>
        <externalId>true</externalId>
        <inlineHelpText>The id of the ApexClass record that this ApexDoc describes</inlineHelpText>
        <label>ApexClass ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <description>The name of the Apex Class or Interface that this record belongs to.</description>
        <externalId>true</externalId>
        <inlineHelpText>The name of the Apex Class or Interface that this record belongs to.</inlineHelpText>
        <label>File Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ModelType__c</fullName>
        <description>The type of data record this is.  It can be CLASS, METHOD, PROPERTY.</description>
        <inlineHelpText>The type of data record this is.  It can be CLASS, METHOD, PROPERTY.</inlineHelpText>
        <label>Model Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Code Info</label>
    <nameField>
        <displayFormat>CIN-{000000000}</displayFormat>
        <label>Code Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Code Info</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CodeInfosSelector.cls
public class CodeInfosSelector
    extends fflib_SObjectSelector
    implements ICodeInfosSelector
{
    public static ICodeInfosSelector newInstance()
    {
        return (ICodeInfosSelector) Application.Selector.newInstance(CodeInfo__c.SObjectType);
    }

    public list<Schema.SObjectField> getSObjectFieldList()
    {
        return new list<Schema.SObjectField>
        {
            CodeInfo__c.Id,
            CodeInfo__c.Name,
            CodeInfo__c.CreatedDate,
            CodeInfo__c.CreatedById,
            CodeInfo__c.LastModifiedDate,
            CodeInfo__c.LastModifiedById,
            CodeInfo__c.OwnerId,
            CodeInfo__c.ModelType__c,
            CodeInfo__c.ApexClassId__c,
            CodeInfo__c.FileName__c
        };
    }

    public Schema.SObjectType getSObjectType()
    {
        return CodeInfo__c.sObjectType;
    }

    public list<CodeInfo__c> selectById(set<id> idSet)
    {
        return (list<CodeInfo__c>) selectSObjectsById(idSet);
    }

    public list<CodeInfo__c> selectByApexClassNameWithClassLinks(set<string> fileNameSet)
    {
    	fflib_QueryFactory mainQueryFactory = newQueryFactory().setCondition(CodeInfo__c.Filename__c + ' in :fileNameSet');

		new ClassLinksSelector().addQueryFactorySubselect( mainQueryFactory );

		new AttachmentsSelector().addQueryFactorySubselect( mainQueryFactory );

    	return Database.query( mainQueryFactory.toSOQL() );
    }

    public list<CodeInfo__c> selectAll()
    {
    	return Database.query( newQueryFactory().toSOQL() );
    }
}